
// This file was auto-generated by ML.NET Model Builder. 

using EvalModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
EvalModel.ModelInput sampleData = new EvalModel.ModelInput()
{
    Col1 = 500F,
    Col2 = 0F,
    Col3 = 0F,
    Col4 = 900F,
    Col5 = 1000F,
    Col6 = 0F,
    Col7 = 300F,
    Col8 = 500F,
    Col9 = 0F,
    Col10 = 100F,
    Col11 = 100F,
    Col12 = 0F,
    Col13 = 0F,
    Col14 = 100F,
    Col15 = -900F,
    Col16 = 100F,
    Col17 = 100F,
    Col18 = 0F,
    Col19 = 300F,
    Col20 = 0F,
    Col21 = 0F,
    Col22 = -1000F,
    Col23 = 0F,
    Col24 = 0F,
    Col25 = 0F,
    Col26 = 0F,
    Col27 = 0F,
    Col28 = 100F,
    Col29 = 100F,
    Col30 = 0F,
    Col31 = 0F,
    Col32 = 0F,
    Col33 = 0F,
    Col34 = 0F,
    Col35 = 0F,
    Col36 = 0F,
    Col37 = 0F,
    Col38 = 0F,
    Col39 = 0F,
    Col40 = 0F,
    Col41 = 0F,
    Col42 = -100F,
    Col43 = 0F,
    Col44 = 0F,
    Col45 = -100F,
    Col46 = 0F,
    Col47 = 0F,
    Col48 = 0F,
    Col49 = -100F,
    Col50 = -350F,
    Col51 = -100F,
    Col52 = -100F,
    Col53 = 0F,
    Col54 = -1000F,
    Col55 = 0F,
    Col56 = -100F,
    Col57 = -500F,
    Col58 = -300F,
    Col59 = 0F,
    Col60 = 0F,
    Col61 = 0F,
    Col62 = -350F,
    Col63 = 0F,
    Col64 = -500F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");


Console.WriteLine($"Col0: {-274F}");
Console.WriteLine($"Col1: {500F}");
Console.WriteLine($"Col2: {0F}");
Console.WriteLine($"Col3: {0F}");
Console.WriteLine($"Col4: {900F}");
Console.WriteLine($"Col5: {1000F}");
Console.WriteLine($"Col6: {0F}");
Console.WriteLine($"Col7: {300F}");
Console.WriteLine($"Col8: {500F}");
Console.WriteLine($"Col9: {0F}");
Console.WriteLine($"Col10: {100F}");
Console.WriteLine($"Col11: {100F}");
Console.WriteLine($"Col12: {0F}");
Console.WriteLine($"Col13: {0F}");
Console.WriteLine($"Col14: {100F}");
Console.WriteLine($"Col15: {-900F}");
Console.WriteLine($"Col16: {100F}");
Console.WriteLine($"Col17: {100F}");
Console.WriteLine($"Col18: {0F}");
Console.WriteLine($"Col19: {300F}");
Console.WriteLine($"Col20: {0F}");
Console.WriteLine($"Col21: {0F}");
Console.WriteLine($"Col22: {-1000F}");
Console.WriteLine($"Col23: {0F}");
Console.WriteLine($"Col24: {0F}");
Console.WriteLine($"Col25: {0F}");
Console.WriteLine($"Col26: {0F}");
Console.WriteLine($"Col27: {0F}");
Console.WriteLine($"Col28: {100F}");
Console.WriteLine($"Col29: {100F}");
Console.WriteLine($"Col30: {0F}");
Console.WriteLine($"Col31: {0F}");
Console.WriteLine($"Col32: {0F}");
Console.WriteLine($"Col33: {0F}");
Console.WriteLine($"Col34: {0F}");
Console.WriteLine($"Col35: {0F}");
Console.WriteLine($"Col36: {0F}");
Console.WriteLine($"Col37: {0F}");
Console.WriteLine($"Col38: {0F}");
Console.WriteLine($"Col39: {0F}");
Console.WriteLine($"Col40: {0F}");
Console.WriteLine($"Col41: {0F}");
Console.WriteLine($"Col42: {-100F}");
Console.WriteLine($"Col43: {0F}");
Console.WriteLine($"Col44: {0F}");
Console.WriteLine($"Col45: {-100F}");
Console.WriteLine($"Col46: {0F}");
Console.WriteLine($"Col47: {0F}");
Console.WriteLine($"Col48: {0F}");
Console.WriteLine($"Col49: {-100F}");
Console.WriteLine($"Col50: {-350F}");
Console.WriteLine($"Col51: {-100F}");
Console.WriteLine($"Col52: {-100F}");
Console.WriteLine($"Col53: {0F}");
Console.WriteLine($"Col54: {-1000F}");
Console.WriteLine($"Col55: {0F}");
Console.WriteLine($"Col56: {-100F}");
Console.WriteLine($"Col57: {-500F}");
Console.WriteLine($"Col58: {-300F}");
Console.WriteLine($"Col59: {0F}");
Console.WriteLine($"Col60: {0F}");
Console.WriteLine($"Col61: {0F}");
Console.WriteLine($"Col62: {-350F}");
Console.WriteLine($"Col63: {0F}");
Console.WriteLine($"Col64: {-500F}");


var predictionResult = EvalModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Col0: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

